if (NOT raylib_FOUND)
    # if (NOT MSVC)
    #     INCLUDE(FetchContent)
    #     FetchContent_Declare(raylib URL https://github.com/raysan5/raylib/archive/refs/tags/4.0.0.tar.gz)
    #     FetchContent_GetProperties(raylib)

    #     if (NOT raylib_POPULATED)
    #         SET(FETCHCONTENT_QUIET NO)
    #         FetchContent_Populate(raylib)
    #         SET(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    #         set(RAYLIB_INCLUDE_DIR ${raylib_SOURCE_DIR}/src)
    #         set(RAYLIB_INCLUDE_DIRS ${raylib_SOURCE_DIR}/src)
    #         set(RAYLIB_LIBRARY ${raylib_BINARY_DIR})
    #         # ADD_SUBDIRECTORY(${raylib_SOURCE_DIR} ${raylib_BINARY_DIR})
    #         SET(raylib_FOUND TRUE)
    #     endif()
    # else()
    INCLUDE(FetchContent)
    FetchContent_Declare(raylib URL https://github.com/raysan5/raylib/archive/refs/tags/4.0.0.tar.gz)
    FetchContent_GetProperties(raylib)

    if (NOT raylib_POPULATED)
        SET(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(raylib)
        SET(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        set(RAYLIB_INCLUDE_DIR ${raylib_SOURCE_DIR}/src)
        set(RAYLIB_INCLUDE_DIRS ${raylib_SOURCE_DIR}/src)
        set(RAYLIB_LIBRARY ${raylib_BINARY_DIR})
        # ADD_SUBDIRECTORY(${raylib_SOURCE_DIR} ${raylib_BINARY_DIR})
        SET(raylib_FOUND TRUE)
    endif()
    # endif()
endif()
