#!/usr/bin/env python3
##
## EPITECH PROJECT, 2022
## 303make
## File description:
## Main
##

from sys import argv
from src.utils import error, usage
from src.MakeGraph import MakeGraph

def build(makeGraph):
    makeGraph.build_matrix()
    makeGraph.build_adjacency()


def display(makeGraph):
    makeGraph.print_matrix()
    print("")
    makeGraph.print_adjacency()


def main():
    if len(argv) != 2 and len(argv) != 3:
        error("Too little arguments, use flag \"-h\" for usage")
    # sys.setrecursionlimit(10**6)
    # file = argument_parsing(argv)
    # data = get_file_content(file[0])
    if argv[1] == "-h":
        usage()

    makeGraph = MakeGraph(argv[1])
    build(makeGraph)
    display(makeGraph)
    return 0

if __name__ == '__main__':
    main()
