##
## EPITECH PROJECT, 2021
## Project Name
## File description:
## Makefile
##

all:
				make -C ./asm/     all
				make -C ./corewar/ all

clean:
				make -C ./asm/     clean
				make -C ./corewar/ clean

fclean:
				make -C ./asm/     fclean
				make -C ./corewar/ fclean

re:
				make -C ./asm/     re
				make -C ./corewar/ re

.PHONY:			all clean fclean re
