version: '3'
services:
  front:
    build:
      context: ./front
    ports:
      - "8081:8081"
    networks:
      area-net:
        ipv4_address: 172.20.0.6
    environment:
      - API_URL=http://back:8080/api/
    command: ["flutter", "run", "-d", "web-server", "--web-port=8081", "--web-hostname=0.0.0.0"]

  back:
    build:
      context: ./back
    ports:
      - "8080:8080"

    volumes:
      - ./back:/app
    networks:
      area-net:
        ipv4_address: 172.20.0.7


  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - back
    networks:
      - area-net


networks:
  area-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
