#!/usr/bin/env python3

##
## EPITECH PROJECT, 2022
## 204ducks
## File description:
## 204ducks
##

from sys import argv, exit
from time import time

from utils import print_usage, error
from param_handling import check_params, get_params
from Ducks import Ducks

def main():
    """ Main entry """
    if len(argv) != 2:
        error("Wrong arguments.\nDo `./204ducks -h` to see usage.")
    if len(argv) == 2 and argv[1] == "-h":
        print_usage()
    ducks = Ducks()

    a = get_params()
    check_params(a)

    ducks.set_time(a)
    ducks._wolfram_alpha()
    ducks.print()

if __name__ == '__main__':
    main()

