#!/usr/bin/env python3
##
## EPITECH PROJECT, 2020
## 108trigo
## File description:
## 108trigo
##

from sys import argv, exit, stderr

from handle_matrix import error_handling, get_matrix, get_matrix_size, print_matrix
from products import get_funcs

def check_valid_function(user_func):
    valid_funcs = ["COS", "SIN", "EXP", "COSH", "SINH"]

    for func in range(len(valid_funcs)):
        if (user_func == valid_funcs[func]):
            return 1
    return 0

def main():
    funcs = get_funcs()

    if (len(argv) == 2 and argv[1] == "-h"):
        error_handling(0)
    if len(argv) < 3:
        error_handling(84)
    try:
        func = str(argv[1])
        if check_valid_function(func) == 0:
            print("HELP: ./108trigo -h", file=stderr)
            exit(84)
        x = get_matrix(get_matrix_size(argv))
    except Exception as e:
        print("108trigo: %s\nHELP: ./108trigo -h" % (e), file=stderr)
        exit(84)

    x = funcs[func](x)
    print_matrix(x)
    return 0

if __name__ == '__main__':
    main()
