##
## EPITECH PROJECT, 2021
## dante (Workspace)
## File description:
## Makefile
##

all:
			make all	-C ./my/
			make all	-C ./stack/

clean:
			make clean	-C ./my/
			make clean	-C ./stack/


fclean:
			make fclean	-C ./my/
			make fclean	-C ./stack/


re:			fclean all
			make re		-C ./my/
			make re		-C ./stack/

.PHONY:		all clean fclean re
