#!/usr/bin/env python3
##
## EPITECH PROJECT, 2022
## 205IQ
## File description:
## 205IQ
##

from sys import argv
from time import time

from utils import usage, error
from param_handling import check_params, get_params
from IQ import IQ

def main():
    """ Main entry """
    if len(argv) < 2 or len(argv) > 5:
        error(f"Wrong arguments.\nDo `{argv[0]} -h` to see usage.")
    if len(argv) == 2 and argv[1] == "-h":
        usage()
    params = get_params()
    check_params(params)
    iq = IQ(params)
    iq.run()

if __name__ == '__main__':
    main()
